spring:
  kafka:
    bootstrap-servers: localhost:9092
    # (Eventuali altre impostazioni Spring Kafka, come producer, template, ecc.)

    # CONSUMER
    consumer:
      group-id: smartcity-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        # consenti al Deserializer di fidarsi dei tuoi model
        spring.json.trusted.packages: com.smartcity.common.model

  data:
    mongodb:
      host: localhost
      port: 27017
      database: smartcity

# ------------------------------------------------------
# Qui inizia la sezione “kafka.topic.sensor-data” al livello root
kafka:
  topic:
    sensor-data: sensor-data
# ------------------------------------------------------

# Opzionale: configurazioni relative a scheduler o parametri di processamento
processor:
  temperatura:
    soglia: 25.0

# application.yml (o application-<profile>.yml)
server:
  port: 8081


