spring:
  kafka:
    bootstrap-servers: localhost:9092

    # PRODUCER
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

# topic dedicato, che poi recuperi con @Value("${kafka.topic.sensor-data}")
kafka:
  topic:
    sensor-data: sensor-data

  simulator:
    publish-interval-ms: 5000
